version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: sajalshres/recommendmemovies-app:latest
    ports:
      - 3000:3000
    container_name: airbnb-analysis-app
