```{r import-data, warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)
library(caret)
library(data.table)
library(dplyr)
library(lubridate)
library(stringr)
library(tidyr)
library(ggplot2)
```


```{r}
raw_data <- tempfile()
download.file("http://files.grouplens.org/datasets/movielens/ml-10m.zip", raw_data)
```

```{r}
ratings <-
  fread(
    text = gsub("::", "\t", readLines(unzip(
      raw_data, "ml-10M100K/ratings.dat"
    ))),
    col.names = c("userId", "movieId", "rating", "timestamp")
  )
```


```{r}
movies <-
  str_split_fixed(readLines(unzip(raw_data, "ml-10M100K/movies.dat")), "\\::", 3)

colnames(movies) <- c("movieId", "title", "genres")
```

```{r}
movies <-
  as.data.frame(movies) %>% mutate(
    movieId = as.numeric(movieId),
    title = as.character(title),
    genres = as.character(genres)
  )


movies_join <- left_join(ratings, movies, by = "movieId")
```

```{r}
set.seed(631, sample.kind="Rounding")

test_index <- createDataPartition(y = movies_join$rating, times = 1, p = 0.1, list = FALSE)
data <- movies_join[-test_index,]
temp <- movies_join[test_index,]

validation <- temp %>% 
  semi_join(data, by = "movieId") %>%
  semi_join(data, by = "userId")

removed <- anti_join(temp, validation)
data <- rbind(data, removed)

rm(raw_data, ratings, movies, test_index, temp, movies_join, removed)
gc()
options(digits = 5)
```

```{r}
rating_by_popularity <- data %>% 
  group_by(movieId) %>% 
  summarize(n_movie = n(), 
            moviemean = mean(rating))

plot_moviepop <- rating_by_popularity %>% 
  ggplot(aes(n_movie, moviemean)) + 
  geom_smooth() +
  ggtitle("Average rating vs number of ratings") +
  labs(x = "Number of ratings", y = "Average rating")

data <- data %>% 
  left_join(rating_by_popularity %>% dplyr::select(-moviemean), by = "movieId")
validation <- validation %>% 
  left_join(rating_by_popularity %>% dplyr::select(-moviemean), by = "movieId")

gc()
```


```{r}
rating_by_freqrater <- data %>% 
  group_by(userId) %>% 
  summarize(n_user = n(), 
            usermean = mean(rating))

## plot the average rating versus user's number of rating
plot_rating_hist <- data %>% 
  group_by(rating) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(rating, n)) + 
  geom_bar(stat="identity") +
  ggtitle("Frequency of each rating")

plot_freqrater <- rating_by_freqrater %>% 
  ggplot(aes(n_user, usermean)) + 
  geom_smooth() +
  ggtitle("Average rating vs user's number of rating") +
  labs(x = "User's number of ratings", y = "Average rating")
##

data <- data %>% 
  left_join(rating_by_freqrater %>% dplyr::select(-usermean), by = "userId")
validation <- validation %>% 
  left_join(rating_by_freqrater %>% dplyr::select(-usermean), by = "userId")

gc()
```


```{r}
movie_mean <- data %>% 
  group_by(movieId) %>% 
  summarize(movieMean = mean(rating), 
            movieMeanStdError = sd(rating)/sqrt(n()))

data <- data %>% 
  left_join(movie_mean, by = "movieId") %>% 
  mutate(movieMeanStdError = replace_na(movieMeanStdError, 5))
validation <- validation %>% 
  left_join(movie_mean, by = "movieId") %>% 
  mutate(movieMeanStdError = replace_na(movieMeanStdError, 5))

gc()
```

```{r}
user_mean <- data %>% 
  group_by(userId) %>% 
  summarize(userMean = mean(rating), 
            userMeanStdError = sd(rating)/sqrt(n()))

data <- data %>% 
  left_join(user_mean, by = "userId") %>% 
  mutate(userMeanStdError = replace_na(userMeanStdError, 5))
validation <- validation %>% 
  left_join(user_mean, by = "userId") %>% 
  mutate(userMeanStdError = replace_na(userMeanStdError, 5))

gc()
```

```{r}
data <-
  data %>% mutate(
    movieYear = as.numeric(str_replace(
      str_replace(str_extract(title, "\\([0-9]{4}\\)"), "\\(", ""), "\\)", ""
    )),
    rateYear = year(as_datetime(timestamp)),
    rateMonth = month(as_datetime(timestamp)),
    rateDay = day(as_datetime(timestamp)),
    rateWday = wday(as_datetime(timestamp)),
    rateHour = hour(as_datetime(timestamp))
  )
```


```{r}
validation <-
  validation %>% mutate(
    movieYear = as.numeric(str_replace(
      str_replace(str_extract(title, "\\([0-9]{4}\\)"), "\\(", ""), "\\)", ""
    )),
    rateYear = year(as_datetime(timestamp)),
    rateMonth = month(as_datetime(timestamp)),
    rateDay = day(as_datetime(timestamp)),
    rateWday = wday(as_datetime(timestamp)),
    rateHour = hour(as_datetime(timestamp))
  )

gc()
```


```{r}
genre_rating_by_year <- data %>%
  group_by(genres) %>%
  summarize(
    n = n(),
    genreMean = mean(rating),
    genreMeanStdError = sd(rating) / sqrt(n)
  ) %>%
  filter(n > 0.0025 * 9000055) %>%
  dplyr::select(-n)

data <- data %>%
  left_join(genre_rating_by_year, by = "genres") %>%
  mutate(
    genreMean = replace_na(genreMean, 5),
    genreMeanStdError = replace_na(genreMeanStdError, 5)
  )
validation <- validation %>%
  left_join(genre_rating_by_year, by = "genres") %>%
  mutate(
    genreMean = replace_na(genreMean, 5),
    genreMeanStdError = replace_na(genreMeanStdError, 5)
  )

gc()
```

```{r}
user_sd <- data %>%
  group_by(userId) %>%
  summarize(userSD = sd(rating))

data <- data %>%
  left_join(user_sd, by = "userId") %>%
  mutate(userSD = replace_na(userSD, 5))

validation <- validation %>%
  left_join(user_sd, by = "userId") %>%
  mutate(userSD = replace_na(userSD, 5))

gc()
```

```{r}
movie_sd <- data %>%
  group_by(movieId) %>%
  summarize(movieSD = sd(rating))

data <- data %>%
  left_join(movie_sd, by = "movieId") %>%
  mutate(movieSD = replace_na(movieSD, 5))

validation <- validation %>%
  left_join(movie_sd, by = "movieId") %>%
  mutate(movieSD = replace_na(movieSD, 5))

gc()
```

```{r}
shorttitle <- function(string) {
  str_trunc(string, str_locate(string, "\\(")[1] + 2, "right")
}

titles <-
  data.frame(title = unique(data[, "title"])) %>% mutate(titleshort = unlist(lapply(title, shorttitle)),
                                                         titlewords = str_count(titleshort, "( )"))

titlelen_mean <- data[, 1:6] %>%
  left_join(titles[, c("title", "titlewords")], by = "title") %>%
  group_by(titlewords) %>%
  summarize(
    n = n(),
    mean = mean(rating),
    stderr = sd(rating) / sqrt(n)
  )
```


```{r}
data <- data %>%
  left_join(titles[, c("title", "titlewords")], by = "title")
validation <- validation %>%
  left_join(titles[, c("title", "titlewords")], by = "title")

gc()
```

```{r}
## model fitting
fit.low <- lm(rating ~
                movieMean +
                userMean +
                n_movie,
              data = data[, -c("userId", "movieId", "timestamp", "title", "genres")])

lmfitbest <- step(
  fit.low,
  scope = list(
    lower = rating ~
      movieMean +
      userMean +
      n_movie,
    upper = rating ~
      n_movie +
      n_user +
      movieMean +
      movieMeanStdError +
      userMean +
      userMeanStdError +
      movieYear +
      rateYear +
      rateMonth +
      rateDay +
      rateWday +
      rateHour +
      genreMean +
      genreMeanStdError +
      userSD +
      movieSD +
      titlewords
  ),
  direction = "both"
)
```

```{r}
summary(lmfitbest)
```


```{r}
bound <- function(x,a,b){max(min(x,b),a)}
```

```{r}
data$y_hat <-
  sapply(predict.lm(lmfitbest, newdata = data),
         bound,
         a = 0.5,
         b = 5)

RMSE(data$y_hat, data$rating)

gc()
```

```{r}
validation$y_hat <- sapply(predict.lm(lmfitbest, newdata = validation),bound,a=0.5,b=5)

RMSE(validation$y_hat,validation$rating)

gc()
```

```{r}
save.image("data/data.RData")
```

```{r}
saveRDS(validation, "data/validation.Rds", compress = TRUE)
saveRDS(lmfitbest, "data/lmfitbest.Rds", compress = TRUE)
saveRDS(data, "data/data.Rds", compress = TRUE)
```

```{r}
lmfitbest <- readRDS("data/lmfitbest.Rds")
```

```{r fig.width=12, fig.height=12}
library("ggfortify")
residual_plot <- ggplot2::autoplot(lmfitbest)
```

```{r}
residual_plot
```


```{r}
saveRDS(summary(lmfitbest), "data/model_summary.Rds", compress = TRUE)
```


